langugage: julia

os:
  - osx
  - linux

julia: 1.0

matrix:
  allow_failures:
    - julia: 1.0

after_success:
  - julia -e 'using Pkg; Pkg.dir("OceanBoundaryLayerModels"); include(joinpath("docs", "make.jl"))'
